.TH "/var/www/chamador.itep.govrn/public/api Directory Reference" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBimprimir\fP"
.br
.ti -1c
.RI "directory \fBlogin\fP"
.br
.ti -1c
.RI "directory \fBmainPage\fP"
.br
.ti -1c
.RI "directory \fBmenu\fP"
.br
.ti -1c
.RI "directory \fBpainel\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClassCompany\&.php\fP"
.br
.RI "Contem a Classe com as informações da Empresa\&. "
.ti -1c
.RI "file \fBClassConnection\&.php\fP"
.br
.ti -1c
.RI "file \fBClassCredenciais\&.php\fP"
.br
.RI "Contem a Classe que gerencia a credencial do Funcionário\&. "
.ti -1c
.RI "file \fBClassFicha\&.php\fP"
.br
.ti -1c
.RI "file \fBClassLogs\&.php\fP"
.br
.ti -1c
.RI "file \fBClassSetor\&.php\fP"
.br
.ti -1c
.RI "file \fBClassUsuario\&.php\fP"
.br
.ti -1c
.RI "file \fBHeader\&.php\fP"
.br
.RI "Contem todo o cabeçalho com classes e funções gerais do sistema\&. "
.ti -1c
.RI "file \fBHeaderJSON\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.in -1c
