.TH "/var/www/chamador.itep.govrn/public/api/mainPage Directory Reference" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/mainPage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBheader\fP"
.br
.ti -1c
.RI "directory \fBinicial\fP"
.br
.ti -1c
.RI "directory \fBpainelGeral\fP"
.br
.ti -1c
.RI "directory \fBperfil\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.in -1c
