.TH "/var/www/chamador.itep.govrn/public/api/imprimir/ficha Directory Reference" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/imprimir/ficha Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.in -1c
