.TH "/var/www/chamador.itep.govrn/public/api/menu/configuracoes/usuarios Directory Reference" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/menu/configuracoes/usuarios Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdelete\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBnew\&.php\fP"
.br
.ti -1c
.RI "file \fBpassword\&.php\fP"
.br
.RI "Contem a lógica para resetar a senha de um usuários do sistema\&. "
.ti -1c
.RI "file \fBupdate\&.php\fP"
.br
.in -1c
