.TH "/var/www/chamador.itep.govrn/public/api/mainPage/inicial Directory Reference" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/mainPage/inicial Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBatendidos\&.php\fP"
.br
.RI "Contem a lógica para gerenciar as fichas não atendidas do setor\&. "
.ti -1c
.RI "file \fBemAtendimento\&.php\fP"
.br
.RI "Contem a lógica para gerenciar as fichas em atendimento do usuário\&. "
.ti -1c
.RI "file \fBencaminhar\&.php\fP"
.br
.RI "Contem a lógica para encaminhar uma ficha a outro setor\&. "
.ti -1c
.RI "file \fBfinalizar\&.php\fP"
.br
.RI "Contem a lógica para finalizar uma ficha em atendimento\&. "
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBnaoAtendidos\&.php\fP"
.br
.RI "Contem a lógica para gerenciar as fichas não atendidas do setor\&. "
.ti -1c
.RI "file \fBnaoAtendidosProximo\&.php\fP"
.br
.ti -1c
.RI "file \fBnaoAtendidosProximoIndividual\&.php\fP"
.br
.RI "Contem a lógica para gerenciar uma chamada de ficha individual\&. "
.in -1c
