.TH "/var/www/chamador.itep.govrn/public/api/ClassCredenciais.php" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/ClassCredenciais.php \- Contem a Classe que gerencia a credencial do Funcionário\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassCredenciais\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contem a Classe que gerencia a credencial do Funcionário\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
28-02-2020
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 DIGETI ITEP/RN 
.RE
.PP

.PP
Definition in file \fBClassCredenciais\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chamador ITEP - API from the source code\&.
