.TH "ClassCredenciais" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassCredenciais
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($login, $password)"
.br
.RI "Funcionário Logado no Sistema\&. "
.ti -1c
.RI "\fBget_user\fP ()"
.br
.RI "Obter Funcionário do Sistema\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ClassCredenciais\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $login,  $password)"

.PP
Funcionário Logado no Sistema\&. Construtor do Objeto \fBClassCredenciais\fP
.PP
\fBParameters:\fP
.RS 4
\fIlogin\fP Login do Funcionário 
.br
\fIpassword\fP Senha do Funcionário 
.RE
.PP

.PP
Definition at line 24 of file ClassCredenciais\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "get_user ()"

.PP
Obter Funcionário do Sistema\&. 
.PP
\fBReturns:\fP
.RS 4
\fBClassUsuario\fP Duncionáriodo Sistema 
.RE
.PP

.PP
Definition at line 58 of file ClassCredenciais\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chamador ITEP - API from the source code\&.
