.TH "ClassCompany" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassCompany
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.RI "Rodapé de impressão\&. "
.ti -1c
.RI "\fB__destruct\fP ()"
.br
.RI "Destrutor da class atribuindo os valores\&. "
.ti -1c
.RI "\fBget_name\fP ()"
.br
.RI "Obter nome da Empresa\&. "
.ti -1c
.RI "\fBget_company_logo\fP ()"
.br
.RI "Obter Logo da Empresa\&. "
.ti -1c
.RI "\fBget_footer_print\fP ()"
.br
.RI "Obter texto de rodapé da impressão\&. "
.ti -1c
.RI "\fBset_footer_print\fP ($value)"
.br
.RI "Definir texto de rodapé da impressão\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ClassCompany\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Rodapé de impressão\&. Construtor da class atribuindo os valores 
.PP
Definition at line 24 of file ClassCompany\&.php\&.
.SS "__destruct ()"

.PP
Destrutor da class atribuindo os valores\&. 
.PP
Definition at line 35 of file ClassCompany\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "get_company_logo ()"

.PP
Obter Logo da Empresa\&. 
.PP
\fBReturns:\fP
.RS 4
Object Logo da Empresa 
.RE
.PP

.PP
Definition at line 66 of file ClassCompany\&.php\&.
.SS "get_footer_print ()"

.PP
Obter texto de rodapé da impressão\&. 
.PP
\fBReturns:\fP
.RS 4
Object Texto de rodapé da impressão 
.RE
.PP

.PP
Definition at line 86 of file ClassCompany\&.php\&.
.SS "get_name ()"

.PP
Obter nome da Empresa\&. 
.PP
\fBReturns:\fP
.RS 4
String Nomde da Empresa 
.RE
.PP

.PP
Definition at line 46 of file ClassCompany\&.php\&.
.SS "set_footer_print ( $value)"

.PP
Definir texto de rodapé da impressão\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP Objeto com o texto de rodapé da impressão 
.RE
.PP

.PP
Definition at line 96 of file ClassCompany\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chamador ITEP - API from the source code\&.
