.TH "/var/www/chamador.itep.govrn/public/api/mainPage/inicial/encaminhar.php" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/mainPage/inicial/encaminhar.php \- Contem a lógica para encaminhar uma ficha a outro setor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dados\fP = []"
.br
.RI "Cabeçalho para conteudo json\&. "
.ti -1c
.RI "\fB$body\fP = file_get_contents('php://input')"
.br
.RI "Contem todos os dados a serem enviados\&. "
.ti -1c
.RI "\fB$json\fP = json_decode($body, true)"
.br
.RI "Obtém todas as informações requisitadas POST\&. "
.ti -1c
.RI "\fB$login\fP = $json['login']"
.br
.RI "Decodifica as informações requisitadas\&. "
.ti -1c
.RI "\fB$senha\fP = $json['senha']"
.br
.RI "Login do usuário que requisitou a informação\&. "
.ti -1c
.RI "\fB$ficha_id\fP = $json['ficha_id']"
.br
.RI "Senha criptografada do usuário que requisitou a informação\&. "
.ti -1c
.RI "\fB$setor_id\fP = $json['setor_id']"
.br
.RI "id da ficha que será encaminhada "
.ti -1c
.RI "\fBtry\fP"
.br
.RI "id do setor que a ficha será encamihada "
.ti -1c
.RI "\fB$ficha\fP = new \fBClassFicha\fP($ficha_id)"
.br
.RI "Obter a credencial do usário\&. "
.ti -1c
.RI "\fB$setor\fP = new \fBClassSetor\fP($setor_id)"
.br
.RI "Obter a ficha pelo id\&. "
.ti -1c
.RI "\fB$log\fP = new \fBClassLogs\fP(null, $credenciais\->get_user(), 'ENCAMINHOU FICHA', $ficha, $setor)"
.br
.ti -1c
.RI "\fBcatch\fP(Exception $e) \fBfinally\fP"
.br
.RI "Criar um log desta operação no sistema\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contem a lógica para encaminhar uma ficha a outro setor\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27-03-2020
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 DIGETI ITEP/RN 
.RE
.PP

.PP
Definition in file \fBencaminhar\&.php\fP\&.
.SH "Variable Documentation"
.PP 
.SS "$body = file_get_contents('php://input')"

.PP
Contem todos os dados a serem enviados\&. 
.PP
Definition at line 21 of file encaminhar\&.php\&.
.SS "$dados = []"

.PP
Cabeçalho para conteudo json\&. Cabeçalho com as classes e funções gerias 
.PP
Definition at line 19 of file encaminhar\&.php\&.
.SS "$ficha = new \fBClassFicha\fP($ficha_id)"

.PP
Obter a credencial do usário\&. 
.PP
Definition at line 32 of file encaminhar\&.php\&.
.SS "$ficha_id = $json['ficha_id']"

.PP
Senha criptografada do usuário que requisitou a informação\&. 
.PP
Definition at line 27 of file encaminhar\&.php\&.
.SS "$json = json_decode($body, true)"

.PP
Obtém todas as informações requisitadas POST\&. 
.PP
Definition at line 22 of file encaminhar\&.php\&.
.SS "$log = new \fBClassLogs\fP(null, $credenciais\->get_user(), 'ENCAMINHOU FICHA', $ficha, $setor)"

.PP
Definition at line 46 of file encaminhar\&.php\&.
.SS "$login = $json['login']"

.PP
Decodifica as informações requisitadas\&. 
.PP
Definition at line 24 of file encaminhar\&.php\&.
.SS "$senha = $json['senha']"

.PP
Login do usuário que requisitou a informação\&. 
.PP
Definition at line 25 of file encaminhar\&.php\&.
.SS "$setor = new \fBClassSetor\fP($setor_id)"

.PP
Obter a ficha pelo id\&. 
.PP
Definition at line 33 of file encaminhar\&.php\&.
.SS "$setor_id = $json['setor_id']"

.PP
id da ficha que será encaminhada 
.PP
Definition at line 28 of file encaminhar\&.php\&.
.SS "\fBcatch\fP (Exception $e) finally"
\fBInitial value:\fP
.PP
.nf
{
    echo json_encode($dados[0])
.fi
.PP
Criar um log desta operação no sistema\&. 
.PP
Definition at line 52 of file encaminhar\&.php\&.
.SS "try"
\fBInitial value:\fP
.PP
.nf
{
    $credenciais = new ClassCredenciais($login, $senha)
.fi
.PP
id do setor que a ficha será encamihada 
.PP
Definition at line 30 of file encaminhar\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chamador ITEP - API from the source code\&.
