.TH "/var/www/chamador.itep.govrn/public/api/mainPage/perfil/formulario.php" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/mainPage/perfil/formulario.php \- Contem a lógica para modificar senha do usuário logado\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dados\fP = []"
.br
.RI "Cabeçalho para conteudo json\&. "
.ti -1c
.RI "\fB$body\fP = file_get_contents('php://input')"
.br
.RI "Contem todos os dados a serem enviados\&. "
.ti -1c
.RI "\fB$json\fP = json_decode($body, true)"
.br
.RI "Obtém todas as informações requisitadas POST\&. "
.ti -1c
.RI "\fB$login\fP = $json['login']"
.br
.RI "Decodifica as informações requisitadas\&. "
.ti -1c
.RI "\fB$senha\fP = $json['senha']"
.br
.RI "Login do usuário que requisitou a informação\&. "
.ti -1c
.RI "\fB$nova_senha\fP = \fBencrypt_password\fP($json['novaSenha'])"
.br
.RI "Senha criptografada do usuário que requisitou a informação\&. "
.ti -1c
.RI "\fBtry\fP"
.br
.RI "Nova senha do usuário já criptografada\&. "
.ti -1c
.RI "\fB$log\fP = new \fBClassLogs\fP(null, $credenciais\->get_user(), 'ATUALIZOU PERFIL', null, null)"
.br
.ti -1c
.RI "\fBcatch\fP(Exception $e) \fBfinally\fP"
.br
.RI "Criar um log desta operação no sistema\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contem a lógica para modificar senha do usuário logado\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
05-03-2020
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 DIGETI ITEP/RN 
.RE
.PP

.PP
Definition in file \fBformulario\&.php\fP\&.
.SH "Variable Documentation"
.PP 
.SS "$body = file_get_contents('php://input')"

.PP
Contem todos os dados a serem enviados\&. 
.PP
Definition at line 21 of file formulario\&.php\&.
.SS "$dados = []"

.PP
Cabeçalho para conteudo json\&. Cabeçalho com as classes e funções gerias 
.PP
Definition at line 19 of file formulario\&.php\&.
.SS "$json = json_decode($body, true)"

.PP
Obtém todas as informações requisitadas POST\&. 
.PP
Definition at line 22 of file formulario\&.php\&.
.SS "$log = new \fBClassLogs\fP(null, $credenciais\->get_user(), 'ATUALIZOU PERFIL', null, null)"

.PP
Definition at line 40 of file formulario\&.php\&.
.SS "$login = $json['login']"

.PP
Decodifica as informações requisitadas\&. 
.PP
Definition at line 24 of file formulario\&.php\&.
.SS "$nova_senha = \fBencrypt_password\fP($json['novaSenha'])"

.PP
Senha criptografada do usuário que requisitou a informação\&. 
.PP
Definition at line 27 of file formulario\&.php\&.
.SS "$senha = $json['senha']"

.PP
Login do usuário que requisitou a informação\&. 
.PP
Definition at line 25 of file formulario\&.php\&.
.SS "\fBcatch\fP (Exception $e) finally"
\fBInitial value:\fP
.PP
.nf
{
    echo json_encode($dados[0])
.fi
.PP
Criar um log desta operação no sistema\&. 
.PP
Definition at line 46 of file formulario\&.php\&.
.SS "try"
\fBInitial value:\fP
.PP
.nf
{
    $credenciais = new ClassCredenciais($login, $senha)
.fi
.PP
Nova senha do usuário já criptografada\&. 
.PP
Definition at line 29 of file formulario\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chamador ITEP - API from the source code\&.
