.TH "/var/www/chamador.itep.govrn/public/api/HeaderJSON.php" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/HeaderJSON.php
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Chamador ITEP - API from the source code\&.
