.TH "/var/www/chamador.itep.govrn/public/api/mainPage/inicial/naoAtendidos.php" 3 "Mon Apr 6 2020" "Chamador ITEP - API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/var/www/chamador.itep.govrn/public/api/mainPage/inicial/naoAtendidos.php \- Contem a lógica para gerenciar as fichas não atendidas do setor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dados\fP = []"
.br
.RI "Cabeçalho para conteudo json\&. "
.ti -1c
.RI "\fB$body\fP = file_get_contents('php://input')"
.br
.RI "Contem todos os dados a serem enviados\&. "
.ti -1c
.RI "\fB$json\fP = json_decode($body, true)"
.br
.RI "Obtém todas as informações requisitadas POST\&. "
.ti -1c
.RI "\fB$login\fP = $json['login']"
.br
.RI "Decodifica as informações requisitadas\&. "
.ti -1c
.RI "\fB$senha\fP = $json['senha']"
.br
.RI "Login do usuário que requisitou a informação\&. "
.ti -1c
.RI "\fBtry\fP"
.br
.RI "Senha criptografada do usuário que requisitou a informação\&. "
.ti -1c
.RI "\fB$db\fP = new \fBClassConnection\fP()"
.br
.RI "Obter a credencial do usário\&. "
.ti -1c
.RI "\fB$today\fP = date('Y\-m\-d')"
.br
.ti -1c
.RI "\fB$sql\fP = 'SELECT * FROM `fichas_tb` WHERE `ficha_criacao_data`>='' \&. $today \&. '' AND `ficha_setor_id`=' \&. $credenciais\->get_user()\->get_sector()\->get_id() \&. ' AND (`ficha_status`='NÃO ATENDIDO' OR `ficha_status`='ENCAMINHADO') ORDER BY `ficha_atualizacao_data` ASC'"
.br
.RI "Obter a data atual\&. "
.ti -1c
.RI "\fB$result\fP = $db\->request_query($sql)"
.br
.ti -1c
.RI "if(mysqli_num_rows($result) > 0) \fBcatch\fP(Exception $e) \fBfinally\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contem a lógica para gerenciar as fichas não atendidas do setor\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
26-03-2020
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 DIGETI ITEP/RN 
.RE
.PP

.PP
Definition in file \fBnaoAtendidos\&.php\fP\&.
.SH "Variable Documentation"
.PP 
.SS "$body = file_get_contents('php://input')"

.PP
Contem todos os dados a serem enviados\&. 
.PP
Definition at line 21 of file naoAtendidos\&.php\&.
.SS "$dados = []"

.PP
Cabeçalho para conteudo json\&. Cabeçalho com as classes e funções gerias 
.PP
Definition at line 19 of file naoAtendidos\&.php\&.
.SS "$db = new \fBClassConnection\fP()"

.PP
Obter a credencial do usário\&. 
.PP
Definition at line 30 of file naoAtendidos\&.php\&.
.SS "$json = json_decode($body, true)"

.PP
Obtém todas as informações requisitadas POST\&. 
.PP
Definition at line 22 of file naoAtendidos\&.php\&.
.SS "$login = $json['login']"

.PP
Decodifica as informações requisitadas\&. 
.PP
Definition at line 24 of file naoAtendidos\&.php\&.
.SS "$result = $db\->request_query($sql)"

.PP
Definition at line 35 of file naoAtendidos\&.php\&.
.SS "$senha = $json['senha']"

.PP
Login do usuário que requisitou a informação\&. 
.PP
Definition at line 25 of file naoAtendidos\&.php\&.
.SS "$sql = 'SELECT * FROM `fichas_tb` WHERE `ficha_criacao_data`>='' \&. $today \&. '' AND `ficha_setor_id`=' \&. $credenciais\->get_user()\->get_sector()\->get_id() \&. ' AND (`ficha_status`='NÃO ATENDIDO' OR `ficha_status`='ENCAMINHADO') ORDER BY `ficha_atualizacao_data` ASC'"

.PP
Obter a data atual\&. 
.PP
Definition at line 34 of file naoAtendidos\&.php\&.
.SS "$today = date('Y\-m\-d')"

.PP
Definition at line 31 of file naoAtendidos\&.php\&.
.SS "if (mysqli_num_rows( $result) > 0) \fBcatch\fP (Exception $e) finally"
\fBInitial value:\fP
.PP
.nf
{
    echo json_encode($dados)
.fi
.PP
Definition at line 60 of file naoAtendidos\&.php\&.
.SS "try"
\fBInitial value:\fP
.PP
.nf
{
    $credenciais = new ClassCredenciais($login, $senha)
.fi
.PP
Senha criptografada do usuário que requisitou a informação\&. 
.PP
Definition at line 27 of file naoAtendidos\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Chamador ITEP - API from the source code\&.
