ClassSetor
$id
$name
id do Setor
$admin
Nome do Setor.
$ficha
Se o Setor tem acesso as configurações do sistema.
$deleted
Se o Setor é quem emite fichas.
$created_on_date
Se o Setor foi deletado do sistema.
__construct($id=null, $name=null, $ficha=null, $admin=null)
Data da criaçãodo Setor.
Construtor do Objeto ClassSetor id id do Setor name Nome do Setor ficha Se o Setor tem acesso as configurações do sistema admin Se o Setor tem acesso as configurações do sistema deleted Se o Setor foi deletado do sistema created_on_date Data da criação do Setor
References $db, $result.
__destruct()
Destrutor do Objeto ClassSetor.
get_id()
Obter o id do Setor.
id do Setor
Referenced by set_name, set_admin, set_created_on_date, set_deleted, set_ficha.
get_name()
Obter o Nome do Setor.
Nome do Setor
Referenced by set_name, set_admin, set_created_on_date, set_deleted, set_ficha.
set_name($value)
Definir o Nome do Setor.
value Valor do Nome a ser definido
References $db, $result, get_name, get_id.
get_admin()
Obter se o Setor e do tipo Administrador.
Bool Se o Setor é administrador
Referenced by set_admin.
set_admin(bool $value)
Definir se o Setor é do tipo Administrador.
value Se o setor é do tipo Administrador
References $db, $result, get_admin, get_id, get_name.
get_created_on_date()
Obter a data de criação do Setor.
Timestamp Data de criação do setor no formato TIMESTAMP
Referenced by set_created_on_date.
set_created_on_date($value)
Definir a data de criação do Setor.
value Data de criação do Setor no formato TIMESTAMP
References $db, $result, get_created_on_date, get_id, get_name.
get_deleted()
Obter a informação se o setor já foi deletado Setor.
Bool Se o setor já foi deletado
Referenced by set_deleted.
set_deleted(bool $value)
Definir se o Setor foi deletado.
value Se o setor foi deletado
References $db, $result, get_deleted, get_id, get_name.
get_ficha()
Obter a informação se o setor gerencia as fichas.
Bool Se o setor gerencia as fichas
Referenced by set_ficha.
set_ficha($value)
Definir se o Setor gerencia as fichas.
value Se o setor gerencia as fichas
References $db, $sql, get_ficha, get_id, $result, get_name.