ClassUsuario
$id
$name
id do Funcionário
$sector
Nome do Funcionário.
$login
Objeto Setor do Funcionário.
$password
Login do Funcionário.
$deleted
Senha do Funcionário criptografada em MD5.
$created_on_date
Se o Funcionário foi deletado do sistema.
__construct($id=null, $name=null, $sector=null, $login=null, $password=null)
Data da criação do Funcionário no sistema.
Construtor do Objeto ClassUsuario id id do Funcionário name Nome do Funcionário sector Setor que o Funcionário trabalha login Login do Funcionário no Sistema password Senha do Funcionário no Sistema deleted Se o Funcionário foi deletado do sistema created_on_date Data da criação do Funcionário no Sistema
References $db, $result.
__destruct()
Destrutor do Objeto ClassUsuario.
get_id()
Obter o id do Funcionário.
Int id do Funcionário
Referenced by set_name, set_sector, set_login, set_password, set_deleted.
get_name()
Obter Nome do Funcionário.
String Nome do Funcionário
Referenced by set_name, set_sector, set_login, set_password, set_deleted.
set_name($value)
Definir Nome do Funcionário.
value Novo Nome do Funcionário
References $db, $result, get_name, get_id.
get_sector()
Obter Setor associado ao Funcionário.
ClassSetor Setor do Funcionário
Referenced by set_sector.
set_sector($value)
Definir o Setor associado ao Funcionário.
value Setor do Funcionário
References $db, $result, get_sector, get_id, get_name.
get_login()
Obter o Login do Funcionário.
String Login do Funcionário
Referenced by set_login.
set_login($value)
Definir o Login do Funcioário.
value Novo Login do Funcionário
References $db, $result, get_login, get_id, get_name.
get_password()
Obter a Senha do Funcionário na criptografia md5.
md5 Senha do Funcionário na criptografia md5
Referenced by set_password.
set_password($value)
Definir a Senha do Funcionário na criptografia md5.
value Nova Senha do Funcionário na criptografia md5
References $db, $result, get_password, get_id, get_name.
get_deleted()
Obter a informação se o Funcionário já foi deletado.
Bool Se o Funcionário já foi deletado
Referenced by set_deleted.
set_deleted(bool $value)
Definir se o Funcionário foi deletado.
value Se o Funcionário foi deletado
References $db, $result, get_deleted, get_id, get_name.
get_created_on_date()
Obter a data que o Funcionário foi criado.
Timestamp Data da criação do Funcionário
set_created_on_date($value)
Definir a data que o Funcionário foi criado.
value Data de criação do Funcionário no Sistema em TIMESTAMP