ClassFicha
$id
$number
id da Ficha
$name
Número da Ficha.
$phone
Nome da Ficha.
$attendant_status
Telefone da Ficha.
$attendant_sector
Status da Ficha.
$attendant_user
Setor a ser atendido.
$priority
Funcionário responsável pelo atendimento.
$date
Se a Ficha tem prioridade na chamada.
$date_update
Data de criação da Ficha.
__construct($id=null, $name=null, $phone=null, $attendant_sector=null, $priority=null)
Data da última atualização da Ficha.
Construtor do Objeto ClassFicha id id da Ficha number Número da Ficha name Nome da Ficha phone Telefone da Ficha attendant_status Status da Ficha attendant_sector Setor a ser atendido attendant_user Funcionário responsável pelo atendimento priority Se a Ficha tem prioridade na chamada date Data de criação da Ficha date_update Data da ultima atualização da Ficha
References $db, $result.
__destruct()
Destrutor do Objeto ClassFicha.
References $result.
get_id()
Obter o id da Ficha.
Int id da Ficha
Referenced by set_number, set_name, set_phone, set_attendant_status, set_attendant_sector, set_attendant_user, set_priority.
get_number()
Obter o Número da Ficha.
Int Número da Ficha
Referenced by set_number, set_name, set_phone, set_attendant_status, set_attendant_sector, set_attendant_user, set_priority.
set_number(int $value)
Definir o Número da Ficha.
value Número da Ficha
References $db, $result, get_number, get_id.
get_name()
Obter o Nome da Ficha.
String Nome da Ficha
Referenced by set_name.
set_name($value)
Definir o Nome da Ficha.
value Nome da Ficha
References $db, $result, get_name, get_id, get_number.
get_phone()
Obter o número do Telefone da Ficha.
String Número do Telefone da Ficha
Referenced by set_phone.
set_phone($value)
Definir o Número do Telefone da Ficha.
value Número do Telefone da Ficha
References $db, $result, get_phone, get_id, get_number.
get_attendant_status()
Obter o Status da Ficha.
String Status da Ficha
Referenced by set_attendant_status.
set_attendant_status($value)
Definir o Status da Ficha.
value Status da Ficha [NÃO ATENDIDO, EM ATENDIMENTO, ENCAMINHADO, FINALIZADO, CHAMAR]
References $db, $result, get_attendant_status, get_id, get_number.
get_attendant_sector()
Obter o Setor de atendimento da Ficha.
ClassSetor Setor de atendimento da Ficha
Referenced by set_attendant_sector.
set_attendant_sector($value)
Definir o Setor de atendimento da Ficha.
ClassSetor Setor de atendimento da Ficha
References $db, $result, get_attendant_sector, get_id, get_number.
get_attendant_user()
Obter o Funcionário de Atendimento da Ficha.
ClassUsuario Funcionário de Atendimento da Ficha
Referenced by set_attendant_user.
set_attendant_user($value)
Definir o Funcionário de Atendimento da Ficha.
ClassUsuario Funcionário de Atendimento da Ficha
References $db, $result, get_attendant_user, get_id, get_number.
get_priority()
Obter a Prioridade da Ficha.
Bool Se a Ficha é do tipo prioritária
Referenced by set_priority.
set_priority(bool $value)
Definir a Prioridade da Ficha.
value Se a Ficha é do tipo prioritária
References $db, $result, get_priority, get_id, get_number.
get_date()
Obter a Data de criação da Ficha em TIMESTAMP.
Timestamp Data de criação da Ficha em TIMESTAMP
get_date_update()
Obter a data da última atualização da Ficha.
Timestamp Data da última atualização da Ficha em TIMESTAMP
get_next_number($conn)
Obter próximo número da Ficha do chamador.
conn Conexão com o Banco de Dados já aberta