ClassLogs
$id
$log_usuario_nome
id do log registrado
$log_usuario_setor_nome
Nome do Usuário que criou o Log.
$log_acao
Nome do Setor do Usuário que criou o Log.
$log_de_nome
Ação do Log.
$log_de_setor_nome
Nome do Usuário ou do Setor que sofreu a Ação.
$log_de_numero
Caso a Ação seja para um Usuário, este é o nome do Setor dele.
$log_de_telefone
Número da Ficha que sofreu a Ação.
$log_para_nome
Telefone da Ficha que sofreu a Ação.
$log_ip
Nome do Setor para onde foi encaminhado a Ficha.
$log_data_criacao
ip do Usuário
__construct($id, $user=null, $action=null, $first=null, $second=null)
Data de criação do Log.
Construtor do Objeto ClassLogs id id do Log user Usuário que gerou o log action Ação aplicada pelo Usuário que gerou o log ["CRIOU USUÁRIO","CRIOU SETOR","EXCLUIU USUÁRIO", "EXCLUIU SETOR","ATUALIZOU USUÁRIO","ATUALIZOU SETOR","ATUALIZOU PERFIL","CRIOU FICHA", "CHAMOU FICHA","ENCAMINHOU FICHA","FINALIZOU FICHA"] first Sujeito que sofreu a ação second Possivel segundo Sujeito que sofreu a ação
References $db, $sql, get_log_usuario_nome, get_log_usuario_setor_nome, get_log_acao, get_log_de_nome, get_log_de_setor_nome, get_log_de_numero, get_log_de_telefone, get_log_para_nome, get_log_ip, $result.
__destruct()
Destrutor do Objeto ClassLogs.
get_log_id()
Obter o id do Log.
Int id do Log
get_log_acao()
Obter a Ação do Log.
String Ação do Log
Referenced by __construct.
get_log_usuario_nome()
Obter o nome do Usuário que criou o Log.
String Nome do Usuário que criou o Log
Referenced by __construct.
get_log_usuario_setor_nome()
Obter o nome do Setor do Usuário que criou o Log.
String Nome do Setor do Usuário que criou o Log
Referenced by __construct.
get_log_data_criacao()
Obter a data de criação do Log.
String Data de criação do Log
get_log_de_nome()
Obter o nome do Usuário ou do Setor que sofreu a Ação.
String Nome do Usuário ou do Setor que sofreu a Ação
Referenced by __construct.
get_log_de_setor_nome()
Obter o nome do Setor caso a Ação seja para um Usuário, se não retorna null.
String Nome do Setor
Referenced by __construct.
get_log_de_numero()
Obter o número da Ficha que sofreu a Ação.
String Número da Ficha que sofreu a Ação
Referenced by __construct.
get_log_de_telefone()
Obter o Telefone da Ficha que sofreu a Ação.
String Telefone da Ficha que sofreu a Ação
Referenced by __construct.
get_log_para_nome()
Obter o Nome do Setor para onde foi encaminhado a Ficha.
String Nome do Setor para onde foi encaminhado a Ficha
Referenced by __construct.
get_log_ip()
Obter ip do Usuário.
String ip do Usuário
Referenced by __construct.
set_log_id($id)
definir o id do Log
id id do Log
check_action($action)
Verificar se a Ação é válida.
action Ação gerada Boolean Se a Ação é válida
set_log_acao($action)
Definir a Ação do Log.
action Ação gerada
set_log_usuario_nome($name)
Definir o nome do Usuário que criou o Log.
name Nome do Usuário que criou o Log
set_log_usuario_setor_nome($name)
Definir o nome do Setor do Usuário que criou o Log.
name Nome do Setor do Usuário que criou o Log
set_log_data_criacao($date)
Definir a data de criação do Log.
date Data de criação do Log
set_log_de_nome($name)
Definir o nome do Usuário ou do Setor que sofreu a Ação.
name Nome do Usuário ou do Setor que sofreu a Ação
set_log_de_setor_nome($name)
Definir o nome do Setor caso a Ação seja para um Usuário, se não retorna null.
name Nome do Setor
set_log_de_numero($number)
Definir o número da Ficha que sofreu a Ação.
number Número da Ficha que sofreu a Ação
set_log_de_telefone($phone)
Definir o Telefone da Ficha que sofreu a Ação.
phone Telefone da Ficha que sofreu a Ação
set_log_para_nome($name)
Definir o Nome do Setor para onde foi encaminhado a Ficha.
name Nome do Setor para onde foi encaminhado a Ficha
set_log_ip($ip)
Definir o ip do Usuário.
ip ip do Usuário